// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNHOptL1UobdwjKsY6atDvP14hZUasGLw',
    appId: '1:254829675866:web:b05ecd49a4a6fe95185f63',
    messagingSenderId: '254829675866',
    projectId: 'gestticket-b0406',
    authDomain: 'gestticket-b0406.firebaseapp.com',
    storageBucket: 'gestticket-b0406.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0PPsWyicXLB_DFpDuhqb-O4LLHSo4viI',
    appId: '1:254829675866:android:229e59f7c267c2d0185f63',
    messagingSenderId: '254829675866',
    projectId: 'gestticket-b0406',
    storageBucket: 'gestticket-b0406.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5IXulumRJHDReaAB_JcqkPL-0ZnaTzHE',
    appId: '1:254829675866:ios:2e37eb459e2e54f6185f63',
    messagingSenderId: '254829675866',
    projectId: 'gestticket-b0406',
    storageBucket: 'gestticket-b0406.appspot.com',
    iosBundleId: 'com.example.gestTickets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5IXulumRJHDReaAB_JcqkPL-0ZnaTzHE',
    appId: '1:254829675866:ios:2e37eb459e2e54f6185f63',
    messagingSenderId: '254829675866',
    projectId: 'gestticket-b0406',
    storageBucket: 'gestticket-b0406.appspot.com',
    iosBundleId: 'com.example.gestTickets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNHOptL1UobdwjKsY6atDvP14hZUasGLw',
    appId: '1:254829675866:web:ec74866c0f28e699185f63',
    messagingSenderId: '254829675866',
    projectId: 'gestticket-b0406',
    authDomain: 'gestticket-b0406.firebaseapp.com',
    storageBucket: 'gestticket-b0406.appspot.com',
  );
}
